server:
  port: 8761

#eureka配置
eureka:
  server:
    enable-self-preservation: false  #是否开启自我保护机制,优先级大于instance的expiration
    eviction-interval-timer-in-ms: 60000 #60秒内不会剔除任何实例
  instance:
    hostname: eureka-server1 #当前主机
    instance-id: ${spring.cloud.client.ip-address}:${server.port}  #实例id
    lease-renewal-interval-in-seconds: 30 #向eureka server发送心跳的间隔
    lease-expiration-duration-in-seconds: 90 #超过90秒eureka server没有收到eureka client的心跳,则剔除该服务

  client:
    service-url:
      defaultZone: http://eureka-server2:8762/eureka #服务端地址
    register-with-eureka: true #是否注册到eureka,除了provider都是false
    fetch-registry: true #是否从Eureka抓取路径,除了consumer都是false

spring:
  application:
    name: eureka-server-ha